Repository therealjamesjung/CodingTestKiller, pull requests merged in 2023-03, with the labels that each got.

#61 [부정빈] 1,2,3더하기-9095, 이항계수2-11051, 동전-9084, LCS-9251
  DP/1,2,3더하기-9095/jeongbinboo.py
  DP/LCS-9251/jeongbinboo.py
  DP/동전-9084/jeongbinboo.py
  DP/이항계수2-11051/jeongbinboo.py
Labels: DP

#60 [노동욱] 1,2,3더하기-9095, 이항계수2-11051, 동전-9084, LCS-9251
  DP/1,2,3더하기-9095/7ngenious.py
  DP/LCS-9251/7ngenious.py
  DP/동전-9084/7ngenious.py
  DP/이항계수2-11051/7ngenious.py
Labels: DP

#59 [김민수] 123더하기-9095, 이항계수2-11051, 동전-9084, LCS-9251
  DP/1,2,3더하기-9095/kmsu44.py
  DP/LCS-9251/kmsu44.py
  DP/동전-9084/kmsu44.py
  DP/이항계수2-11051/kmsu44.py
Labels: DP

#54 [송인제] 1,2,3더하기-9095, 이항계수2-11051, 동전-9084, LCS-9251
  DP/1,2,3더하기-9095/ssongjay.py
  DP/LCS-9251/ssongjay.py
  DP/동전-9084/ssongjay.py
  DP/이항계수2-11051/ssongjay.py
Labels: DP

#57 [이우식] 123더하기-9095, 이항계수2-11051, 동전-9084, LCS-9251
  DP/1,2,3더하기-9095/yireal.py
  DP/LCS-9251/yireal.py
  DP/동전-9084/yireal.py
  DP/이항계수2-11051/yireal.py
Labels: DP

#56 [홍성철] 1,2,3더하기-9095, 이항계수2-11051, 동전-9084, LCS-9251
  DP/1,2,3더하기-9095/ironAiken2.py
  DP/LCS-9251/ironAiken2.py
  DP/동전-9084/ironAiken2.py
  DP/이항계수2-11051/ironAiken2.py
Labels: DP

#58 [정재경] 123더하기-9095, 이항계수2-11051, 동전-9084, LCS-9251
  DP/1,2,3더하기-9095/therealjamesjung.py
  DP/LCS-9251/therealjamesjung.py
  DP/동전-9084/therealjamesjung.py
  DP/이항계수2-11051/therealjamesjung.py
Labels: DP

#55 [김경원] 1,2,3더하기-9095, 이항계수2-11051, 동전-9084, LCS-9251
  DP/1,2,3더하기-9095/masonkimseoul.py
  DP/LCS-9251/masonkimseoul.py
  DP/동전-9084/masonkimseoul.py
  DP/이항계수2-11051/masonkimseoul.py
Labels: DP

#66 [이우식]/ 주지수-15724, 포도주 시식 -2156, 평범한 배낭 -12865, 선수과목-14567
  DP/선수과목-14567/yireal.py
  DP/주지수-15724/yireal.py
  DP/평범한배낭-12865/yireal.py
  DP/포도주시식-2156/yireal.py
Labels: DP

#65 [부정빈] / 주지수-15724, 포도주 시식 -2156, 평범한 배낭 -12865, 선수과목-14567
  DP/선수과목-14567/jeongbinboo.py
  DP/주지수-15724/jeongbinboo.py
  DP/평범한배낭-12865/jeongbinboo.py
  DP/포도주시식-2156/jeongbinboo.py
Labels: DP

#63 [홍성철] / 주지수-15724, 포도주 시식 -2156, 평범한 배낭 -12865, 선수과목-14567
  DP/선수과목-14567/ironAiken2.py
  DP/주지수-15724/ironAiken2.py
  DP/평범한배낭-12865/ironAiken2.py
  DP/포도주시식-2156/ironAiken2.py
Labels: DP

#64 [정재경] / 주지수-15724, 포도주 시식 -2156, 평범한 배낭 -12865, 선수과목-14567
  DP/선수과목-14567/therealjamesjung.py
  DP/주지수-15724/therealjamesjung.py
  DP/평범한배낭-12865/therealjamesjung.py
  DP/포도주시식-2156/therealjamesjung.py
Labels: DP

#68 [노동욱] / 주지수-15724, 포도주 시식 -2156, 평범한 배낭 -12865, 선수과목-14567
  DP/선수과목-14567/7ngenious.py
  DP/주지수-15724/7ngenious.py
  DP/평범한배낭-12865/7ngenious.py
  DP/포도주시식-2156/7ngenious.py
Labels: DP

#69 [정재경] / 한이가사-2422, 넴모넴모-14712, 계란으로계란깨기-16987, N-Queen-9663
  백트래킹/N-Queen-9663/therealjamesjung.py
  백트래킹/계란으로계란깨기-16987/therealjamesjung.py
  백트래킹/넴모넴모-14712/therealjamesjung.py
  완전탐색/한이가사-2422/therealjamesjung.py
Labels: 백트래킹

#70 [홍성철] / 한이가사-2422, 넴모넴모-14712, 계란으로계란깨기-16987, N-Queen-9663
  백트래킹/N-Queen-9663/ironAiken2.py
  백트래킹/계란으로계란치기-16987/ironAiken2.py
  백트래킹/넴모넴모-14712/ironAiken2.py
  완전탐색/한이가사-2422/ironAiken2.py
Labels: 백트래킹

#72 [이우식] / 한이가사-2422, 넴모넴모-14712, 계란으로계란깨기-16987, N-Queen-9663
  백트래킹/N-Queen-9663/yireal.py
  백트래킹/계란으로계란치기-16987/yireal.py
  백트래킹/넴모넴모-14712/yireal.py
  완전탐색/한이가사-2422/yireal.py
Labels: 백트래킹

#75 [김민수] / 한이가사-2422, 넴모넴모-14712, 계란으로계란깨기-16987, N-Queen-9663
  백트래킹/N-Queen-9663/kmsu44.py
  백트래킹/계란으로계란치기-16987/kmsu44.py
  백트래킹/넴모넴모-14712/kmsu44.py
  완전탐색/한이가사-2422/kmsu44.py
Labels: 백트래킹

#74 [김경원] / 한이가사-2422, 넴모넴모-14712, 계란으로계란깨기-16987, N-Queen-9663
  백트래킹/N-Queen-9663/masonkimseoul.py
  백트래킹/계란으로계란깨기-16987/masonkimseoul.py
  백트래킹/넴모넴모-14712/masonkimseoul.py
  완전탐색/한이가사-2422/masonkimseoul.py
Labels: 백트래킹

#73 [송인제] / 한이가사-2422, 넴모넴모-14712, 계란으로계란깨기-16987, N-Queen-9663
  백트래킹/N-Queen-9663/ssongjay.py
  백트래킹/계란으로계란치기-16987/ssongjay.py
  백트래킹/넴모넴모-14712/ssongjay.py
  완전탐색/한이가사-2422/ssongjay.py
Labels: 백트래킹

#79 [이우식] / 거스름돈-14916, 센서-2217, 택배-8980, A->B-16953
  그리디/A->B-16953/yireal.py
  그리디/거스름돈-14916/yireal.py
  그리디/센서-2212/yireal.py
  그리디/택배-8980/yireal.py
Labels: 그리디

#78 [정재경] / 거스름돈-14916, 센서-2212, 택배-8980, A->B-16953
  그리디/A->B-16953/therealjamesjung.py
  그리디/거스름돈-14916/therealjamesjung.py
  그리디/센서-2212/therealjamesjung.py
  그리디/택배-8980/therealjamesjung.py
Labels: 그리디

#76 [김민수] / 거스름돈-14916, 센서-2212, 택배-8980, A->B-16953
  그리디/A->B-16953/kmsu44.py
  그리디/거스름돈-14916/kmsu44.py
  그리디/센서-2212/kmsu44.py
  그리디/택배-8980/kmsu44.py
Labels: 그리디

#82 [송인제] / 거스름돈-14916, 센서-2217, 택배-8980, A->B-16953
  그리디/A-B-16953/ssongjay.py
  그리디/거스름돈-14916/ssongjay.py
  그리디/센서-2212/ssongjay.py
  그리디/택배-8980/ssongjay.py
Labels: 그리디

#80 [김경원] / 거스름돈-14916, 센서-2212, 택배-8980, A->B-16953
  그리디/A->B-16953/masonkimseoul.py
  그리디/거스름돈-14916/masonkimseoul.py
  그리디/센서-2212/masonkimseoul.py
  그리디/택배-8980/masonkimseoul.py
Labels: 그리디

#88 [김경원] / 배열합치기-11728, 겹치는건싫어-20922, 회전초밥-15961, 같이눈사람만들래-20366
  투포인터/같이눈사람만들래?-20366/masonkimseoul.py
  투포인터/겹치는건싫어-20922/masonkimseoul.py
  투포인터/배열합치기-11728/masonkimseoul.py
  투포인터/회전초밥-15961/masonkimseoul.py
Labels: 투포인터

#84 [김민수] / 배열합치기-11728, 곂치는건싫어-20922, 회전초밥-15961, 같이눈사람만들래-20366
  투포인터/같이눈사람만들래?-20366/kmsu44.py
  투포인터/겹치는건싫어-20922/kmsu44.py
  투포인터/배열합치기-11728/kmsu44.py
  투포인터/회전초밥-15961/kmsu44.py
Labels: 투포인터

#85 [이우식] / 배열합치기-11728, 곂치는건싫어-20922, 회전초밥-15961, 같이눈사람만들래-20366
  투포인터/같이눈사람만들래?-20366/yireal.py
  투포인터/겹치는건싫어-20922/yireal.py
  투포인터/배열합치기-11728/yireal.py
  투포인터/회전초밥-15961/yireal.py
Labels: 투포인터

#86 [정재경] / 배열합치기-11728, 겹치는건싫어-20922, 회전초밥-15961, 같이눈사람만들래-20366
  투포인터/같이눈사람만들래?-20366/therealjamesjung.py
  투포인터/겹치는건싫어-20922/therealjamesjung.py
  투포인터/배열합치기-11728/therealjamesjung.py
  투포인터/회전초밥-15961/therealjamesjung.py
Labels: 투포인터

#83 [홍성철] / 배열합치기-11728, 곂치는건싫어-20922, 회전초밥-15961, 같이눈사람만들래-20366
  투포인터/같이눈사람만들래?-20366/ironAiken2.py
  투포인터/겹치는건싫어-20922/ironAiken2.py
  투포인터/배열합치기-11728/ironAiken2.py
  투포인터/회전초밥-15961/ironAiken2.py
Labels: 투포인터
